//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Head
    {
        public int Head_ID { get; set; }
        public string Head_Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Instid { get; set; }
        public Nullable<int> Campid { get; set; }
        public Nullable<int> Status { get; set; }
        public string ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    }
}
