//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campu
    {
        public int Campid { get; set; }
        public Nullable<int> Instid { get; set; }
        public string Campdesc { get; set; }
        public string Campshortdesc { get; set; }
        public Nullable<int> Countid { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<int> Stateid { get; set; }
        public string Addedby { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedt { get; set; }
        public string ActvStatus { get; set; }
    }
}
