//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DEPTID { get; set; }
        public Nullable<int> INSTID { get; set; }
        public Nullable<int> CAMPID { get; set; }
        public string DEPTNAME { get; set; }
        public string DEPTDESCRIPTION { get; set; }
        public string ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
    
        public virtual Campu Campu { get; set; }
        public virtual Campu Campu1 { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual Institution Institution1 { get; set; }
    }
}
