//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialYear
    {
        public int FINCID { get; set; }
        public int INSTID { get; set; }
        public int CAMPID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string STARTMON { get; set; }
        public string ENDMON { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISACTIVE { get; set; }
        public string ADDEDBY { get; set; }
        public Nullable<System.DateTime> ADDEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDT { get; set; }
    }
}
