//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution_vw
    {
        public int Instid { get; set; }
        public string Instdesc { get; set; }
        public string Instshortdesc { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string addedby { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> Updatedt { get; set; }
    }
}
