//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program_vw
    {
        public int Progid { get; set; }
        public string ProgDesc { get; set; }
        public string Progshortdesc { get; set; }
        public string Instdesc { get; set; }
        public string Campdesc { get; set; }
        public string Addedby { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> Updatedt { get; set; }
        public string ActvStatus { get; set; }
    }
}
