//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTS_SMSEntities : DbContext
    {
        public TTS_SMSEntities()
            : base("name=TTS_SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Campu> Campus { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Institution_vw> Institution_vw { get; set; }
        public virtual DbSet<Campus_vw> Campus_vw { get; set; }
        public virtual DbSet<Program_vw> Program_vw { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Class_vw> Class_vw { get; set; }
        public virtual DbSet<Term_vw> Term_vw { get; set; }
        public virtual DbSet<Domicile> Domiciles { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Admission_mst> Admission_mst { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<Session_vw> Session_vw { get; set; }
        public virtual DbSet<AcadStatu> AcadStatus { get; set; }
        public virtual DbSet<Admission_vw> Admission_vw { get; set; }
        public virtual DbSet<Account_Head> Account_Head { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Frequency> Frequencies { get; set; }
        public virtual DbSet<Fees_Structure> Fees_Structure { get; set; }
    }
}
