//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystemTTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int TermId { get; set; }
        public string TermName { get; set; }
        public string TermDescription { get; set; }
        public Nullable<int> INSTID { get; set; }
        public Nullable<int> CAMPID { get; set; }
        public Nullable<int> Progid { get; set; }
        public string Addedby { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ActvStatus { get; set; }
    }
}
